apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::376129850044:user/DE000058
      username: DE000058
      groups:
        - system:masters

