name: Build and Deploy to K8s on AWS

on:
  # push:               # trigger chạy tự động
  #   branches:
  #     - dev   
  #     - main 
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -f app.api/app.dockerfile  -t trunghua75/max-weather:${{ github.sha }} .
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push trunghua75/max-weather:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy to K8s from deployment.yaml
      run: |
        ENV=prod
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          ENV=dev
        fi
        
        echo "+++++++++ Current env deploy: ${ENV}"
        sed -i "s|ENV|${ENV}|g" app.api/k8s/deployment.yaml
        sed -i "s|CONTAINER_APP_URI|trunghua75/max-weather:${{ github.sha }}|g" app.api/k8s/deployment.yaml
        sed -i "s|ENV|${ENV}|g" app.api/k8s/certificate.yaml
        sed -i "s|ENV|${ENV}|g" app.api/k8s/service.yaml
        sed -i "s|ENV|${ENV}|g" app.api/k8s/ingress.yaml

        echo "+++++++++ Preview deployment"
        cat app.api/k8s/deployment.yaml
        cat app.api/k8s/certificate.yaml
        cat app.api/k8s/service.yaml
        cat app.api/k8s/ingress.yaml

        echo "+++++++++ Apply deployment"
        kubectl apply -f app.api/k8s/deployment.yaml
        kubectl apply -f app.api/k8s/service.yaml
        kubectl apply -f app.api/k8s/ingress.yaml
        kubectl apply -f app.api/k8s/certificate.yaml

        echo "+++++++++ Checking rollout status        
        kubectl rollout status deployment/app-api -n max-weather-${ENV}     
  
  testing:
    needs: deploy
    runs-on: ubuntu-latest

    steps:

      - name: Test Run ping back from Pod API 
        run: |
          ENV=prod
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            ENV=dev
          fi
          echo "Process Ping back"
          URL="https://${ENV}-api.odoo.id.vn/v1/ping"
          MAX_RETRIES=5
          DELAY=2
          attempt=0
          sleep 10

          # Function to perform curl request
          while (( attempt < MAX_RETRIES )); do
              echo "Attempt $((attempt + 1)) to test URL: $URL"
              curl --fail --silent --show-error "$URL" && {
                  echo "URL responded successfully."
                  exit 0
              }
              ((attempt++))
              if (( attempt < MAX_RETRIES )); then
                  echo "Retrying in $DELAY seconds..."
                  sleep $DELAY
              fi
          done

          # If all attempts fail, throw an error
          echo "Error: URL test failed after $MAX_RETRIES attempts."
          exit 1