name: Init Kubeconfig

on:
  workflow_dispatch:

jobs:
  init-kubeconfig:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: u58-cluster
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get AWS user ARN and username
      id: identity
      run: |
        ARN=$(aws sts get-caller-identity --query Arn --output text)
        echo "arn=$ARN" >> $GITHUB_OUTPUT
        echo "username=$(echo $ARN | awk -F'/' '{print $NF}')" >> $GITHUB_OUTPUT

    - name: Grant access to EKS cluster
      run: |
        aws eks create-access-entry \
          --cluster-name $CLUSTER_NAME \
          --principal-arn ${{ steps.identity.outputs.arn }} \
          --type STANDARD \
          --user ${{ steps.identity.outputs.username }} \
          --kubernetes-groups Viewers \
          --region $AWS_REGION

        aws eks associate-access-policy \
          --cluster-name $CLUSTER_NAME \
          --access-scope type=cluster \
          --principal-arn ${{ steps.identity.outputs.arn }} \
          --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
          --region $AWS_REGION

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

        echo "✅ Current context:"
        kubectl config current-context

        echo "📦 All namespaces in EKS:"
        kubectl get namespace -A
